"""daily quote history

Revision ID: a2cf6f516ed4
Revises: 02ebe77d96cd
Create Date: 2026-10-05 01:56:25.533949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf6f516ed4'
down_revision: Union[str, None] = '02ebe77d96cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=True),
    sa.Column('self_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['self_message_id'], ['self_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quote_date', name='uq_daily_quotes_user_date')
    )
    op.create_index(op.f('ix_daily_quotes_quote_date'), 'daily_quotes', ['quote_date'], unique=False)
    op.create_index(op.f('ix_daily_quotes_user_id'), 'daily_quotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_quotes_user_id'), table_name='daily_quotes')
    op.drop_index(op.f('ix_daily_quotes_quote_date'), table_name='daily_quotes')
    op.drop_table('daily_quotes')
    # ### end Alembic commands ###
